
# Site settings
title: "Yao Yin's Cyperspace"
email: InYuo1997@gmail.com
description: "Yao Yin's Personal Website"
baseurl: ""
url: "https://yin-yao.github.io"
title_description: "Hi, this is Yao Yin. Welcome to my website. 欢迎光临！ようこそ！\n\n I love the world of math and computer science as a software engineer. This website is built to record and share my thoughts and notes.
\n\n My avatar is Xiaoludan (小卤蛋), the cat kept by my dear girlfriend."
title_image: "/images/xiaoludan_avatar.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/yao-yin/yao-yin.github.io/tree/gh-pages
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: CreamEggMeat
github_username:  yao-yin
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/yin-yao-54457b12a/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/CreamEggMeat\">Yao Yin</a>"
footer_right: "&lt;/&gt; Jekyll theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a> on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]